### ISSUE TITLE
[git bash] npm ERR! path C:\...\amazon-cognito-example-for-external-idp/package.json

### ISSUE THREAD

**Issue by isgallagher** [aws-samples/amazon-cognito-example-for-external-idp#133]
Hello,

I am trying to run this from git bash on Windows.  When I run `./install.sh` I get the error about package.json missing.  I have tried creating an empty file containing `{}` and then I get an error about 

```
53 verbose reify failed optional dependency C:\...\amazon-cognito-example-for-external-idp\lambda\api\node_modules\fsevents
...
67 verbose stack TypeError: Cannot read properties of undefined (reading 'spec')
67 verbose stack     at updateNodes (C:\...\nvm\v18.13.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:1193:44)
67 verbose stack     at [saveIdealTree] (C:\..\nvm\v18.13.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:1362:11)
67 verbose stack     at Arborist.reify (C:\..\nvm\v18.13.0\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:157:31)
67 verbose stack     at async Install.exec (C:\..\nvm\v18.13.0\node_modules\npm\lib\commands\install.js:145:5)
67 verbose stack     at async module.exports (C:\..\nvm\v18.13.0\node_modules\npm\lib\cli.js:78:5)
```

I think I must be doing something wrong.  Is the package.json file needed?  If so, was it deleted from the repo on accident, or how can I recreate it?  Thanks in advance!

**Comment by jhart0** [comment]
I can reproduce this on Windows. I believe it is due to --prefix not working with the npm cli on Windows: https://github.com/npm/cli/issues/1290 

I will keep this issue open as a reminder to fix the scripts for Windows. 

In the meantime, you can either cd into each folder in the install.sh script or run install.sh on a Linux/macOS machine.
