### ISSUE TITLE
Not a functional example

### ISSUE THREAD

**Issue by MushyMiddle** [aws-samples/amazon-cognito-example-for-external-idp#172]
This sample appears to no longer be a functional example with the latest Amplify, CDK, etc.  It should either be corrected, or retired.

Mainly, the non-functional import of "Hub, Auth".  Auth can be worked around, but Hub remains a mystery.

**Comment by jhart0** [comment]
Hi @MushyMiddle , thanks for raising this. 

We are in the process of updating this to the latest amplify and CDK v2. I'll update here once we've merged the changes.

**Comment by jhart0** [comment]
Resolved in #181
