### ISSUE TITLE
Integration of ALB with Cognito

### ISSUE THREAD

**Issue by newtoworld999** [aws-samples/amazon-cognito-example-for-external-idp#23]
Hi 
For set of applications to be authenticated, we are using ALB with Cognito user pools and cognito user pool is using external identity provider. So once the users hits the link it reaches ALB. ALB will redirect to cognito as session doesnt exist and then cognito will talk to IDP and gets authenticated for the user and then cognito generates the tokens and sends that to ALB. ALB will add the header(OIDC headers) information and passes to backend application. IF user clicks on any other page does ALB again redirects to Cognito for the tokens even if the session is valid?
Is there any documentation where i can see the complete authentication flow for ALB+cognito+External IDP(openid)?
I have gone through this link and want to udnerstand if this is correct

https://www.kdgregory.com/index.php?page=aws.albCognito

**Comment by eranation** [comment]
See **Authentication logout and session timeout** around session timeouts [here](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html) (as long as the session is valid uses won't be redirected to Cognito)
