### ISSUE TITLE
"groups" field mapping for the SAML response in G-Suite/Google Workspace

### ISSUE THREAD

**Issue by latacora-tomekr** [aws-samples/amazon-cognito-example-for-external-idp#24]
In the [RBAC Cognito ](https://aws.amazon.com/blogs/security/role-based-access-control-using-amazon-cognito-and-an-external-identity-provider/) article, the IdP configuration section has the step
> Configure the field mapping for the SAML response in the IdP. Map the first name, last name, email, and groups (as a multivalue attribute) into SAML response attributes with the names firstName, lastName, email, **and groups**, respectively.

The section links to Google's [custom SAML setup](https://support.google.com/a/answer/6087519?hl=en) but I've been struggling to find a way to setup the "groups" mapping. This isn't an available attribute in the SAML attribute mapping configuration in Google Workspace.

Are you familiar with a way to set this mapping up in Google Workspace for Groups and/or Organizational Units?

<img width="1184" alt="saml-mapping" src="https://user-images.githubusercontent.com/69216698/99155218-9b1af480-267b-11eb-855d-990874dc7c03.png">

**Comment by eranation** [comment]
Sorry for the delay! This is a great question and unfortunately I don't know the answer. Did you contact Google support? I assume you saw similar results online: https://www.dynatrace.com/support/help/how-to-use-dynatrace/user-management-and-sso/manage-users-and-groups-with-saml/saml-gsuite/ (I haven't tried this approach and not sure if it will work but it seems relevant). I'm closing as it's not a bug with this repo, but please reopen if you still have a follow up question on this or if there is anything I can do in this example to help with the mapping.

**Comment by KamilKopaczyk** [comment]
@millad90s from what i know, you can't currently do this "the right way" using Google Workspace (confirmed by their support) - you can only do this using custom attributes, but you can't use those attributes in search. 
You could use some cloud user directory services like Okta, JumpCloud etc. or if you can afford Google Workspace Enterprise plan you could use custom attributes combined with dynamic groups for easier searching and managing who can do what.

**Comment by fbatschi** [comment]
I think the feature everybody is looking for would be group mapping which is currently only available as beta:
https://support.google.com/a/answer/11143403
