### ISSUE TITLE
Suggestion: add OIDC support

### ISSUE THREAD

**Issue by eranation** [aws-samples/amazon-cognito-example-for-external-idp#47]
The example currently supports SAML, and would be nice to also include an OIDC option. 

This will need 

- update in the env.sh.template file to allow to choose this configuration 
- update readme 
- update `cdk.ts` to include an OIDC option (including auto discovery based on issuer etc)

**Comment by 486** [comment]
I have a working branch of that and would send a PR soon!

**Comment by rajneeshr** [comment]
I've submitted a pull request for this. Could you please take a look @eranation ?

**Comment by eranation** [comment]
I’m no longer with AWS, so I can’t approve but I’ll notify the new owners
:)
