### ISSUE TITLE
Errors in deploy.sh

### ISSUE THREAD

**Issue by wei-m-teh** [aws-samples/amazon-cognito-example-for-external-idp#75]
Hi, I ran into some issues with this workshop. I was able to get through install.sh but deploy.sh failed with the following error:

Building UIs

> amazon-cognito-example-for-external-idp-ui-react@0.2.0 compile-config
> tsc src/config/autoGenConfig.ts

> amazon-cognito-example-for-external-idp-ui-react@0.2.0 build
> react-scripts build

Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Compiled with warnings.

src/components/App.tsx
  Line 55:34:  'window.location.hash' is assigned to itself  no-self-assign

src/config/amplifyConfig.ts
  Line 7:1:  Assign object to a variable before exporting as module default  import/no-anonymous-default-export

src/config/autoGenConfig.js
  Line 1:1:  'use strict' is unnecessary inside of modules  strict

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  200.54 KB  build/static/js/2.04a9f932.chunk.js
  3.83 KB    build/static/js/main.0344c442.chunk.js
  806 B      build/static/js/runtime-main.d3e9f6ae.js
  284 B      build/static/css/main.6f3d0c47.chunk.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  https://cra.link/deployment

> amazon-cognito-example-for-external-idp-ui-angular@0.2.0 build
> ng build

"BuildCustomWebpackBrowserSchema" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
Warning: Using differential loading with targets ES5 and ES2016 or higher may
cause problems. Browsers with support for ES2015 will load the ES2016+ scripts
referenced with script[type="module"] but they may not support ES2016+ syntax.
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @aws-amplify/ui-angular : module as esm5
✔ Browser application bundle generation complete.
⠼ Generating ES5 bundles for differential loading...
⠦ Generating ES5 bundles for differential loading...
⠇ Generating ES5 bundles for differential loading...An unhandled exception occurred: Call retries were exceeded
See "/tmp/ng-Hhnv34/angular-errors.log" for further details.

Some information about my AWS environment:
TeamRole:~/amazon-cognito-example-for-external-idp (master) $ npm -v
8.1.2
TeamRole:~/amazon-cognito-example-for-external-idp (master) $ node -v
v16.11.1

Any suggestions on how to correct this error?

**Comment by rust84** [comment]
Same issue.

**Comment by jhart0** [comment]
This should now be fixed as of #79 . Please reopen this ticket if you are still facing issues.
