### ISSUE TITLE
[Documentation]  Installation section change the order of the steps

### ISSUE THREAD

**Issue by kbband** [aws-samples/amazon-cognito-example-for-external-idp#9]
In the Installation section steps (3) and (4) should come before step (2). You need to Copy env.sh.template to env.sh and Edit env.sh and set the values there based on your environment before you run ./install.sh

**Comment by eranation** [comment]
Thanks! will update the docs

**Comment by eranation** [comment]
Updated README.md, please let me know if there are any other issues, thanks!
