### ISSUE TITLE
Issuer mismatch Microsoft “common” endpoint

### ISSUE THREAD

**Issue by soplan** [aws-samples/amazon-cognito-example-for-external-idp#98]
So apparently Microsoft is not following OIDC. 

To support both personal and Microsoft accounts to  sign up / sign in with cognito as Microsoft as IDP the docs tell you to use “common”

However cognito follows OIDC correctly and returns a bad issuer mismatch error when users try to sign up / log in using a Microsoft account. 
https://github.com/MicrosoftDocs/azure-docs/issues/38427

Other parties such as firebase, okta etc have implemented fix because Microsoft will not comply with OIDC in the near future. 

Can cognito team implement a fix so we can support Microsoft personal and work accounts using “common”?

**Comment by Honda-a** [comment]
Maybe some replys?

**Comment by anil-venkata** [comment]
any idea when can this be implemented..?

**Comment by jhart0** [comment]
The Amazon Cognito team is not monitoring this repository & we can't comment on the roadmap here unfortunately. I would suggest raising this issue with [AWS Support](go.aws/support-center) or via your AWS account team to discuss further.

**Comment by benshaji-sequoiaat** [comment]
#### Update March 13th 2024
This issue still exist. Any Multi-tenant application in Azure-AD *Accounts in any organizational directory (Any Microsoft Entra ID tenant - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)* - When connected with Cognito (via OpenIDC), any users within your organization can login and the Authorization Code will be returned from Cognito.
But, if someone outside of your org tries to sign-in, Cognito returns error exactly mentioned here: https://repost.aws/questions/QUsw4UcwOlS1izHJcCUY8lVA/error-while-implementing-azure-ad-as-oidc-provider-in-aws-cognito-401-error-getting-token . So, i guess this (multi-tenant apps) is not supported in Cognito yet i believe.

**Comment by sainapsisSanvego** [comment]
would be an easy feature to allow a placeholder in the Issuer URL to allow something like https://login.microsoftonline.com/{tenant_id}/v2.0 or https://login.microsoftonline.com/*
And multy tenant federation OIDC with Microsoft is not something cognito should ignore, its a big bloquer for SAS apps that want to use cognito

**Comment by vastarparagopal** [comment]
Is there any updates on this?

**Comment by futureWA** [comment]
This is really disappointing. Cognito is not a serious option without MS Support.

**Comment by OyvindNORMA** [comment]
This is not solcved as far as I can see? Why is it marked solved, it still is an issue.

**Comment by benshaji-sequoiaat** [comment]
I had written a blog nearly a year ago about this https://b3nsh4.com/blog/2024/django-oauth-fullstory/

**Comment by barbaldo** [comment]
Is there a workaround or is this a no go?

**Comment by dehli** [comment]
A workaround is that you could create a "proxy" oidc provider that forwards requests to the common microsoft endpoint and then validates the response before sending it back to cognito. Within your own code, you could handle the template replacing logic before validating that the issuer matches.

**Comment by barbaldo** [comment]
@dehli we thought about it but the overhead of maintaining a custom OIDC provider is a bit too much. We ended up switching IDP
